### ISSUE TITLE
@apply issue

### ISSUE THREAD

**Issue by zidandff** [tailwindlabs/tailwindcss-aspect-ratio#16]
### What version of @tailwindcss/aspect-ratio are you using?

v0.2.1

### What version of Node.js are you using?

v12.18.3

### What browser are you using?

Edge

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/zidandff/tailwind-aspectratio

### Describe your issue

If I wrote the class of **tailwindcss-aspect-ratio** in element attribute is working normally
`<div class="aspect-w-16 aspect-h-9">
    <img src="https://source.unsplash.com/random/500x700" class="object-cover" alt="">
</div>`

however when I want create a component using @apply it doesn't work
`.card {
    @apply aspect-w-9 aspect-h-16;
}`

but when use _aspect-w-1 aspect-h-1_ it's working normally again
`.card {
    @apply aspect-w-1 aspect-h-1;
}`

**Comment by simonswiss** [comment]
Hey!

Thanks for taking the time to create this repro 👍

I can confirm the issue, and looks like there is an open PR for it: 

https://github.com/tailwindlabs/tailwindcss-aspect-ratio/pull/9

**Comment by zidandff** [comment]
Thanks @simonswiss it really help

**Comment by bigskillet** [comment]
This is still isn't working for me with Version 0.3.0, Tailwind 2.2.19. `@apply aspect-w-1 aspect-h-1` works, but other numbers like `@apply aspect-w-16 aspect-h-9` are not.
