### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/functional-purple-black-tree/-/functional-purple-black-tree-1.0.1.tgz: Request failed \"404 Not Found\"".

### ISSUE THREAD

**Issue by zeluizr** [tailwindlabs/tailwindcss-aspect-ratio#18]
### What version of @tailwindcss/aspect-ratio are you using?

v.0.2.0

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

no repo

### Describe your issue

yarn add v1.22.10
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning inmmerce@0.2.0: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/functional-purple-black-tree/-/functional-purple-black-tree-1.0.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in ".../yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by adamwathan** [comment]
Hey! This appears to be a network error or something to do with the `functional-purple-black-tree` package being removed from the registry or similar, and not related to this plugin. If you only see this issue when using this plugin, please open a new issue and include a reproduction, thanks!
