### ISSUE TITLE
JIT mode

### ISSUE THREAD

**Issue by federicocappellotto97** [tailwindlabs/tailwindcss-aspect-ratio#19]
### What version of @tailwindcss/aspect-ratio are you using?

Playground

### What version of Node.js are you using?

Playground

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/lja9H4c3N2

### Describe your issue

Does the plugin work with JIT mode? I'm trying to use it with custom classes, but it doesn't seem to work

**Comment by guar47** [comment]
Same here. Couldn't figure out how to make it works with JIT.

**Comment by pmburov** [comment]
Plugin applies class with css variables but it does not affect layout.

**Comment by bradlc** [comment]
Hey all. We just published `v0.3.0` which adds support for using arbitrary values. This does require Tailwind CSS v3.0.0-alpha.1 so be sure to check out the release notes for that: https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.0-alpha.1

And here's a demo: https://play.tailwindcss.com/eXlnpPcULI

**Comment by st-quando** [comment]
@bradlc how about tailwind 2.2.17 ?
