### ISSUE TITLE
@apply not working

### ISSUE THREAD

**Issue by bigskillet** [tailwindlabs/tailwindcss-aspect-ratio#2]
- `@apply` not working. Tested in both `1.9.6` and `tailwindcss@next (2.0.0-alpha.12)`
- `tailwindcss@next` build is failing with empty `tailwind.config` settings, e.g. `colors {}`

https://github.com/bigskillet/tailwind-aspect-ratio

**Comment by bigskillet** [comment]
Just bumped the dependencies on the test repo, but still not working.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is an issue inside tailwindcss itself. I opened an issue here: https://github.com/tailwindlabs/tailwindcss/issues/3360
I will report back here once the issue is fixed.

**Comment by RobinMalfait** [comment]
Here is a reproduction case in the tailwind playground: https://play.tailwindcss.com/LMtlgPrsqU

**Comment by 27pchrisl** [comment]
@RobinMalfait can this issue be re-opened?

**Comment by simonswiss** [comment]
Bumped into this issue today from another issue opened. We'll look into [your PR](https://github.com/tailwindlabs/tailwindcss-aspect-ratio/pull/9) very soon, @27pchrisl 👍
