### ISSUE TITLE
Add 

### ISSUE THREAD

**Issue by browner12** [tailwindlabs/tailwindcss-aspect-ratio#28]
### What version of @tailwindcss/aspect-ratio are you using?

0.3.0

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

N/A

### Describe your issue

From what I can tell, the `aspect-ratio` property is fully supported in all of the most recent versions of major browsers.

https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

Is it time to migrate this plugin into the main repo, and away from the `padding` hack?

**Comment by adamwathan** [comment]
Hey! Tailwind 3 (out in a week or two) includes native aspect ratio support. This plugin will stick around until Safari 15 is the dominant Safari version.

**Comment by browner12** [comment]
great, thanks for the update.
