### ISSUE TITLE
deprecated - In favor of integrations in core Tailwind 3.0

### ISSUE THREAD

**Issue by Triloworld** [tailwindlabs/tailwindcss-aspect-ratio#31]
### What version of @tailwindcss/aspect-ratio are you using?

0.4.0

### What version of Node.js are you using?

v14.17.2

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

Tailwind 3.0.0 now in core have this plugin! Check official docs

### Describe your issue

By default this plugin is no longer needed for new version.
Pleas block usage of it or write message and in console.log warm about incompatibility.

Doc:
https://tailwindcss.com/docs/aspect-ratio

Right now Plugin remove default one options and replace with one provided in readme.md (not merge plugin and core options)
This isn't needed as can be used in syntax [] for any variants, new options can be defined in tailwindcss.config.js and no need separate plugin.

**Comment by kamilmedrala** [comment]
The fact that the plugin disables default utilities should be mentioned in the documentation.

**Comment by reinink** [comment]
Hey! So this plugin is not deprecated, as it's still useful if you need to support Safari 14, which I suspect most people still do. For example, even on the new Tailwind CSS documentation website we're still using this plugin for all areas that we need aspect ratio support (other than on the new aspect-ratio utilities page, of course).

@kamilmedrala Yes, good call, it's on our TODO list 👍

**Comment by reinink** [comment]
@kamilmedrala Added: https://github.com/tailwindlabs/tailwindcss-aspect-ratio/blob/master/README.md#compatibility-with-default-aspect-ratio-utilities

**Comment by kamilmedrala** [comment]
Looks great!

**Comment by Triloworld** [comment]
About adding plugin in PlayCDN: https://tailwindcss-com-git-fork-triloworld-master-tailwindlabs.vercel.app/docs/installation/play-cdn

Why default settings is exclusive rather inclusive of variety of options?
Adding plugin is a way to add more options. Just editing default setting won't break anything and only be aligned with expectation from newcomers
