### ISSUE TITLE
How to place two iframes next to each other w/ equal height.

### ISSUE THREAD

**Issue by jasikpark** [tailwindlabs/tailwindcss-aspect-ratio#8]
I want to show a youtube livestream and youtube live chat embed next to each other, but I'm having trouble ensuring that they are responsive and the same height.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

You can do something like this: https://play.tailwindcss.com/YGx3HoXeIS
